version: "3.8"

services:
  alfred-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - LOG_LEVEL=DEBUG
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db
    volumes:
      - ../logs:/app/logs
      - ../data/chroma_db:/app/data/chroma_db

  redis:
    image: "redis:6.0-alpine"
    volumes:
      - ../data/redis:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
