version: "3.8"

services:
  api:
    container_name: alfred-bot
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ../logs:/app/logs
      - ../data/chroma_db:/app/data/chroma_db

  redis:
    image: "redis:7.2-alpine"
    volumes:
      - ../data/redis:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
