openapi: 3.0.0
info:
  title: Alfred-Bot API
  description: API documentation for the Alfred-Bot application.
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /chat/:
    post:
      tags:
        - chat
      summary: Main chat endpoint
      description: Main chat endpoint with embedded session handling.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatResponse"
        "500":
          description: Internal server error
  /chat/stats:
    get:
      tags:
        - chat
      summary: Get chat stats
      description: Get chatbot engine statistics.
      responses:
        "200":
          description: Successful response
        "500":
          description: Internal server error
  /chat/session/{session_id}/context:
    get:
      tags:
        - chat
      summary: Get session context
      description: Get current session context and conversation state.
      parameters:
        - in: path
          name: session_id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful response
        "404":
          description: Session not found
        "500":
          description: Internal server error
  /health/:
    get:
      tags:
        - health
      summary: Health check
      description: General application health check.
      responses:
        "200":
          description: Successful response
        "503":
          description: Service unavailable
  /health/redis:
    get:
      tags:
        - health
      summary: Redis health check
      description: Check Redis connection and session manager health.
      responses:
        "200":
          description: Successful response
        "503":
          description: Service unavailable
  /health/chroma:
    get:
      tags:
        - health
      summary: Chroma health check
      description: Check ChromaDB vector store health.
      responses:
        "200":
          description: Successful response
        "503":
          description: Service unavailable
  /health/dependencies:
    get:
      tags:
        - health
      summary: Dependencies health check
      description: Check all dependencies health.
      responses:
        "200":
          description: Successful response
        "503":
          description: Service unavailable
  /health/stats:
    get:
      tags:
        - health
      summary: System stats
      description: Get comprehensive system statistics.
      responses:
        "200":
          description: Successful response
        "500":
          description: Internal server error
  /session/create:
    post:
      tags:
        - session
      summary: Create session
      description: Create a new chat session.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionCreate"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionData"
        "500":
          description: Internal server error
  /session/{session_id}:
    get:
      tags:
        - session
      summary: Get session
      description: Get session by ID.
      parameters:
        - in: path
          name: session_id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionData"
        "404":
          description: Session not found
    delete:
      tags:
        - session
      summary: Delete session
      description: Delete a session.
      parameters:
        - in: path
          name: session_id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful response
        "404":
          description: Session not found
  /session/{session_id}/summary:
    get:
      tags:
        - session
      summary: Get session summary
      description: Get session summary.
      parameters:
        - in: path
          name: session_id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful response
        "404":
          description: Session not found
components:
  schemas:
    ChatRequest:
      type: object
      properties:
        message:
          type: string
        session_id:
          type: string
        user_id:
          type: string
    ChatResponse:
      type: object
      properties:
        intent_id:
          type: string
        response:
          type: string
        session_id:
          type: string
    SessionCreate:
      type: object
      properties:
        user_id:
          type: string
        initial_context:
          type: object
    SessionData:
      type: object
      properties:
        session_id:
          type: string
        user_id:
          type: string
        created_at:
          type: string
          format: date-time
        last_activity:
          type: string
          format: date-time
        context_variables:
          type: object
        conversation_history:
          type: array
          items:
            type: object
